name: Terraform CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-ci:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environment/dev

    steps:

      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Terraform version
      - name: Terraform Version
        run: terraform version

      # Terraform Format
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan
